import Link from 'next/link';

import { StudioNav } from '@/components/studio/studio-nav';
import { formatSocialPostCreatedAt } from '@/server/social-post-format';
import {
  listSocialPostsForUser,
  SocialPostServiceError,
} from '@/server/social-posts';

export const dynamic = 'force-dynamic';

export default async function SocialPostsPage() {
  const resourceId = process.env.CHEKKU_LOCAL_USER_ID || 'local-user';
  let posts: Awaited<ReturnType<typeof listSocialPostsForUser>> = [];
  let errorMessage: string | undefined;

  try {
    posts = await listSocialPostsForUser();
  } catch (error) {
    errorMessage = error instanceof SocialPostServiceError
      ? error.message
      : 'Could not load social posts.';
  }

  return (
    <div className="studio-shell">
      <StudioNav resourceId={resourceId} />
      <main className="studio-main">
        <header className="studio-page-header">
          <div>
            <p className="studio-eyebrow">Garage storage</p>
            <h1>Social posts</h1>
            <p>Instagram drafts generated by the weekly scheduled workflow, ready for review.</p>
          </div>
        </header>

        <section className="studio-section">
          {errorMessage ? (
            <div className="studio-alert studio-alert-error" role="alert">
              {errorMessage}
            </div>
          ) : posts.length === 0 ? (
            <div className="studio-empty-state">
              <h3>No saved drafts</h3>
              <p>Scheduled social posts will appear here after the weekly workflow runs.</p>
            </div>
          ) : (
            <div
              className="studio-report-table-wrap studio-panel"
              tabIndex={0}
              role="region"
              aria-label="Saved social posts"
            >
              <table className="studio-report-table">
                <thead>
                  <tr>
                    <th>Post id</th>
                    <th>Created</th>
                    <th>Topic</th>
                    <th>Special day</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {posts.map((post) => (
                    <tr key={post.postId}>
                      <td>
                        <Link href={`/social-posts/${encodeURIComponent(post.postId)}`}>
                          {post.postId}
                        </Link>
                      </td>
                      <td>{formatSocialPostCreatedAt(post.createdAt)}</td>
                      <td>{post.topic}</td>
                      <td>{post.specialDay ?? '—'}</td>
                      <td>{post.status}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
