'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';

interface CompetitiveSlidesProps {
  analysisId: string;
  slidesMarkdown: string;
  variant?: 'authenticated' | 'public';
  anchorProduct?: string;
  createdAt?: string;
}

interface Rendered {
  html: string;
  css: string;
}

interface SlidePosition {
  current: number;
  total: number;
}

const SCOPED_PRINT_STYLE = `
@media print {
  .competitive-slides-toolbar,
  .competitive-slides-counter,
  .competitive-slides-page-back,
  .public-slides-context {
    display: none !important;
  }
  .competitive-slides-shell,
  .competitive-slides-shell-public {
    height: auto !important;
    display: block !important;
  }
  .competitive-slides-stage {
    height: auto !important;
    overflow: visible !important;
    scroll-snap-type: none !important;
    flex: none !important;
  }
}
`;

export function CompetitiveSlides({
  analysisId,
  slidesMarkdown,
  variant = 'authenticated',
  anchorProduct,
  createdAt,
}: CompetitiveSlidesProps) {
  const [rendered, setRendered] = useState<Rendered | null>(null);
  const [error, setError] = useState(false);
  const [position, setPosition] = useState<SlidePosition>({ current: 1, total: 0 });
  const [isFullscreen, setIsFullscreen] = useState(false);
  const stageRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const { Marp } = await import('@marp-team/marp-core');
        const result = new Marp({ script: false }).render(slidesMarkdown) as Rendered;
        if (cancelled) return;
        setRendered(result);
        setError(false);
      } catch {
        if (cancelled) return;
        setError(true);
        setRendered(null);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [slidesMarkdown]);

  useEffect(() => {
    if (!rendered) return;
    const stage = stageRef.current;
    if (!stage) return;

    const slides = Array.from(stage.querySelectorAll<Element>('svg[data-marpit-svg]'));
    setPosition({ current: 1, total: slides.length });

    if (slides.length === 0) return;

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((entry) => entry.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
        if (!visible) return;
        const index = slides.indexOf(visible.target);
        if (index >= 0) setPosition({ current: index + 1, total: slides.length });
      },
      { threshold: [0.5, 0.75], root: stage },
    );
    slides.forEach((slide) => observer.observe(slide));

    return () => observer.disconnect();
  }, [rendered]);

  useEffect(() => {
    if (!rendered) return;
    const handler = (event: KeyboardEvent) => {
      if (event.key !== 'ArrowRight' && event.key !== 'ArrowLeft') return;
      const stage = stageRef.current;
      if (!stage) return;
      const slides = Array.from(stage.querySelectorAll<Element>('svg[data-marpit-svg]'));
      if (slides.length === 0) return;
      const current = position.current - 1;
      const targetIndex = event.key === 'ArrowRight'
        ? Math.min(current + 1, slides.length - 1)
        : Math.max(current - 1, 0);
      slides[targetIndex]?.scrollIntoView({ behavior: 'smooth' });
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [rendered, position]);

  useEffect(() => {
    const handler = () => setIsFullscreen(Boolean(document.fullscreenElement));
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, []);

  if (error) {
    return (
      <div className="studio-alert studio-alert-error" role="alert">
        <p>Could not render slides.</p>
        <p>
          <Link href={`/reports/competitive/${encodeURIComponent(analysisId)}`}>Back to analysis</Link>
        </p>
      </div>
    );
  }

  const handleFullscreen = () => {
    const stage = stageRef.current;
    if (!stage) return;
    if (document.fullscreenElement) {
      void document.exitFullscreen();
    } else {
      void stage.requestFullscreen();
    }
  };

  if (variant === 'public') {
    return (
      <div className="competitive-slides-shell competitive-slides-shell-public">
        <style dangerouslySetInnerHTML={{ __html: SCOPED_PRINT_STYLE }} />
        <div className="competitive-slides-stage" ref={stageRef}>
          {!rendered ? (
            <p className="competitive-slides-loading">Rendering deck…</p>
          ) : (
            <>
              <style dangerouslySetInnerHTML={{ __html: rendered.css }} />
              <div dangerouslySetInnerHTML={{ __html: rendered.html }} />
            </>
          )}
        </div>
        {anchorProduct && createdAt ? (
          <p className="public-slides-context">
            Generated by Chekku · {anchorProduct} · {createdAt}
          </p>
        ) : null}
      </div>
    );
  }

  return (
    <div className="competitive-slides-shell">
      <style dangerouslySetInnerHTML={{ __html: SCOPED_PRINT_STYLE }} />
      <div className="competitive-slides-toolbar">
        <span className="competitive-slides-counter" aria-live="polite">
          {position.current} / {position.total}
        </span>
        <button type="button" className="studio-button" onClick={() => window.print()}>
          Print
        </button>
        <button type="button" className="studio-button" onClick={handleFullscreen}>
          {isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
        </button>
      </div>
      <div className="competitive-slides-stage" ref={stageRef}>
        {!rendered ? (
          <p className="competitive-slides-loading">Rendering deck…</p>
        ) : (
          <>
            <style dangerouslySetInnerHTML={{ __html: rendered.css }} />
            <div dangerouslySetInnerHTML={{ __html: rendered.html }} />
          </>
        )}
      </div>
    </div>
  );
}
