import { BrandMark } from '@/components/ui/brand-mark';
import {
  listSocialPostsForUser,
  SocialPostServiceError,
} from '@/server/social-posts';
import RunWeeklyDraftsButton from './RunWeeklyDraftsButton';
import SocialPostGrid from './social-post-grid';

export const dynamic = 'force-dynamic';

export default async function SocialPostsPage() {
  let posts: Awaited<ReturnType<typeof listSocialPostsForUser>> = [];
  let errorMessage: string | undefined;

  try {
    posts = await listSocialPostsForUser();
  } catch (error) {
    errorMessage = error instanceof SocialPostServiceError
      ? error.message
      : 'Could not load social posts.';
  }

  return (
    <>
        <header className="studio-page-header">
          <div>
            <p className="studio-eyebrow">Garage storage</p>
            <h1>Social posts</h1>
            <p>Instagram drafts generated by the weekly scheduled workflow, ready for review.</p>
          </div>
          {process.env.NODE_ENV !== 'production' ? <RunWeeklyDraftsButton /> : null}
        </header>

        <section className="studio-section">
          {errorMessage ? (
            <div className="studio-alert studio-alert-error" role="alert">
              {errorMessage}
            </div>
          ) : posts.length === 0 ? (
            <div className="studio-empty-state studio-registry-empty">
              <BrandMark />
              <h3>No saved drafts</h3>
              <p>
                Scheduled social posts appear here after the weekly workflow
                runs (Mondays 09:00 Asia/Jakarta).
              </p>
              {process.env.NODE_ENV !== 'production' ? (
                <RunWeeklyDraftsButton />
              ) : null}
            </div>
          ) : (
            <SocialPostGrid posts={posts} />
          )}
        </section>
    </>
  );
}
